name: sigma_flutter_ui
description: SIGMA Gesture Control UI in Flutter

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # WebSocket 통신
  web_socket_channel: ^2.4.0
  
  # 오버레이 창 관리
  window_manager: ^0.3.7
  
  # JSON 처리
  json_serializable: ^6.7.1
  
  # HTTP 클라이언트
  http: ^1.1.0

  # Camera
  camera: ^0.10.5+9
  path_provider: ^2.1.3
  path: ^1.9.0
  camera_windows: ^0.2.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/